### ISSUE TITLE
CanonicalHeaders are not sorted, cannot use x-amz-content-sha256 

### ISSUE THREAD

**Issue by thefloweringash** [badslug/Paw-AWSSignature4DynamicValue#17]
The [specification of canonical requests] requires that the CanonicalHeaders are sorted.

> CanonicalHeaders is a list of request headers with their values. Individual header name and value pairs are separated by the newline character ("\n"). Header names must be in lowercase. You must sort the header names alphabetically to construct the string

The current implementation both doesn't sort the headers, and places `x-amz-date` before the canonical headers. Trying to use the `x-amz-content-sha256` header will always fail. For such a request, the debug console shows the canonical headers as follows:

```
x-amz-date:20170914T064714Z
x-amz-content-sha256:ae8606b0531703e020a80c7da442d41efc2553c434986c2e4dd432f6ea4175c5
```

While amazon's `SignatureDoesNotMatch` error response includes the following ordering:
```
x-amz-content-sha256:ae8606b0531703e020a80c7da442d41efc2553c434986c2e4dd432f6ea4175c5
x-amz-date:20170914T064226Z
```

[specification of canonical requests]: http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html#canonical-request

**Comment by badslug** [comment]
Thanks for the PR. I've merged and submitted to Lucky Marmot for update in the PAW database.
