### ISSUE TITLE
form fields not included in canonical request

### ISSUE THREAD

**Issue by adphillips** [badslug/Paw-AWSSignature4DynamicValue#2]
Hey this is an awesome extension to PAW. I almost got it to work, then finally did by commenting out this section

```
/* or from the POST body (when Content-Type is
 * application/x-www-form-urlencoded). */
var urlEncodedBody = request.urlEncodedBody
if (urlEncodedBody) {
  for (var key in urlEncodedBody) {
    var value = urlEncodedBody[key]
    params.push([key, value])
  }
}
```

The reason for that being that AWS does not include form params in the conical request.  I found that out by tracing errors in the extensions console of PAW.  This extension includes them and AWS does not when checking the request, so AWS reports that the signatures do not match.  Once i opened the file and commented this part out, all was well.

**Comment by badslug** [comment]
Awesome, thanks. I've patched and posted the release as 1.0.3. I'll ping the guys at Lucky Marmot and they should update their link to it in the plugins directory pretty quickly.
