### ISSUE TITLE
Use for calls to service API?

### ISSUE THREAD

**Issue by dwinter3** [badslug/Paw-AWSSignature4DynamicValue#20]
I'd love to use this just to run things like Describe-instance against ec2. Is that possible?

**Comment by badslug** [comment]
It should be possible. I have only used it for the REST gateway APIs (for a project I was working on) and I think people are using it for the S3 API but you should be able to sign any AWS API that uses the signature 4 headers (should be all the latest versions of AWS APIs). Please try it out and let me know if you encounter any issues. I'd love to know that it works with the EC2 API for sure.

**Comment by scottslowe** [comment]
I'd like to echo the request to be able to use this extension for regular AWS service API endpoints (like EC2). I tried using it, but AWS responds that it is not able to validate the credentials.

macOS version: 10.14.6
Paw version: 3.1.9
Extension version: 1.0.10

<img width="1020" alt="Screen Shot 2020-01-10 at 3 32 47 PM" src="https://user-images.githubusercontent.com/1977326/72191115-7fd9bb80-33be-11ea-82d1-46e4c39f0245.png">

Maybe I'm just using the extension incorrectly...?

**Comment by badslug** [comment]
@scottslowe  I think there may be some issues. I'm not currently running any projects that use the AWS APIs so the most difficult part for me is testing changes against the API. I'm also swamped at work so unfortunately this project gets put on the back burner. I'd love to integrate some PRs if anyone wants to try to fix the issues (hint, hint).  :) 

Otherwise, I'll do my best to improve the compatibility but can't say what the time line would be. I am aware of the issues though.

**Comment by scottslowe** [comment]
@badslug Thanks for your reply. What's the best way to troubleshoot this, to get more detailed information? I'm no programmer, but I'm happy to try to help (and hopefully I can learn a bit more in the process).

**Comment by badslug** [comment]
It's useful to have the full "Raw" request and response from Paw (the right side window).  It's been a while but I'm fairly sure there should not be any personally identifying information in that information. If there is, you can redact it in your pictures before posting (just make sure your AWS account ID and your keys aren't in the output). Thanks

**Comment by scottslowe** [comment]
I am abashed to admit that my errors were apparently user-inflicted. After conducting some additional testing, I learned that specifying a region like "us-west-2" without matching the URL endpoint appropriately (like `https://ec2.us-west-2.amazonaws.com`) will generate the error(s) I was seeing. Once I matched up the URL endpoint with the region, everything works fine---I'm able to issue API calls to EC2 with no problem.

**Comment by badslug** [comment]
@scottslowe absolutely no problem at all. I find the AWS error messages to be extremely vague and misleading - I've been bitten by region mismatch issues MANY times myself.

And it's super great to hear that you can access the EC2 API using Paw and this extension. I'm going to leave this open for another week in case @dwinter3 wants to chime in but I think your tests are enough to mark this issue as closed. 

Thanks again for your help verifying this works for EC2 APIs!
