### ISSUE TITLE
Native Support for STS Credentials (similar to Postman)

### ISSUE THREAD

**Issue by AkshayBhatnagar** [badslug/Paw-AWSSignature4DynamicValue#25]
Today as the library suggests, `X-Amz-Security-Token` needs to be added manually. I was previously using Postman and it has a more comprehensive option of providing the following fields as input:

1. AccessKey
2. SecretKey
3. AWS Region (Optional)
4. Service Name (Optional)
5. Session Token (Optional)

This would allow a much better experience using the extension.

I tried looking into the extension documentation of PAW, but I noticed the class used for input in this extension (DynamicValueInput) was different than the ones listed here: https://paw.cloud/docs/extensions/input-fields . I believe PAW documentation is not up to date. 

Can we add support with similar inputs in this extension?

**Comment by badslug** [comment]
@bhatnagarakshay Thanks for the suggestion - I agree it sounds like a good improvement. I'll investigate but I have to caveat with the fact that I'm super busy so it may take a while. This extension could use a lot more love than I have time to give it. I don't actively use the extension myself so unfortunately it's a low priority for me. Hopefully I can get to it eventually though. (Hint hint, if anyone wants to help out or even take over this extension I'm interested in collaborators).

**Comment by sndpl** [comment]
Just had a look at it, but it seems this isn't possible at the moment because the PAW DynamicValue extensions are not allowed to add/update headers for the request. See also: https://stackoverflow.com/questions/37053611/javascript-extension-error-cannot-perform-modifications/37071761#37071761

**Comment by badslug** [comment]
A follow up, @sndpl is correct. I can set the value but it keeps getting unset (which now that I remember, is why I can't also automatically generate the X-Amz-Date header). Sorry for how long this has sat open but I'm going to close this as a "won't fix". If Paw adds the ability for dynamic values to add headers I'll definitely make this an option (as well as automate the X-Amz-Date header generation).
