### ISSUE TITLE
SHA-256 hash for binary payloads aren't correct

### ISSUE THREAD

**Issue by nilayp** [badslug/Paw-AWSSignature4DynamicValue#29]
I'm using Paw and this extension to PUT images into AWS S3. In order to achieve this, the payload (a JPEG file) needs to have it's SHA-256 properly calculated. However, when I attempt the request in Paw, AWS S3 returns back a "SignatureDoesNotMatch" error. 

In spending some time with this, I believe the problem is how the SHA-256 is being calculated by [this code](https://github.com/badslug/Paw-AWSSignature4DynamicValue/blob/develop/AWSSignature4DynamicValue.js#L240). According to the [Paw Request documentation](https://paw.cloud/docs/reference/Request#body), it appears that `request.body` returns a string. The SHA-256 of the binary object is what is needed in the signature calculation, not that binary object's string representation. 

I tried to convert the request.body string representation back to binary data and take the hash, but couldn't figure it out. My experience understanding what is and isn't possible within the context of Paw's extensions framework is very limited.

I temporarily solved this problem for myself by using the request's `x-amz-content-sha256` header. Because AWS S3 wants you to hash the request body and include it in the request header, I just used this value instead of computing the hash again. While this works for me, I understand that not every AWS request needs a `x-amz-content-sha256` header.

I changed [this code](https://github.com/badslug/Paw-AWSSignature4DynamicValue/blob/develop/AWSSignature4DynamicValue.js#L240) to:

```
 var bodyHash = request.getHeaderByName('x-amz-content-sha256', false)
```

**Comment by jimdelois** [comment]
@nilayp - I was looking into the same issue and discovered your workaround.  This worked for me, so I formalized it into an optional parameter.

cc @badslug In theory it would be ideal to be able to retrieve the binary file (it doesn't seem to be the case that this is possible with Paw's API).  However, this is an additive feature that some people may desire anyway, even outside of our use cases, so it seemed reasonable to me to augment the plugin with this functionality.  Related: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

**Comment by jimdelois** [comment]
Even if we had access to the file path and name, we could update the plugin to issue commands out to the shell to perform the hashing of its contents but, from what I can tell, we cannot obtain this from the Paw API.
