### ISSUE TITLE
Host header not taken into consideration when generating signature

### ISSUE THREAD

**Issue by riy** [badslug/Paw-AWSSignature4DynamicValue#31]
Hey Iain,

First of all: this is an awesome extension!

I ran across one minor issue that prevents us from using it in our setup:
We're tunneling traffic to an ElasticSearch cluster through an SSH tunnel. So our endpoint is `https://localhost...` and not the endpoint ElasticSearch provides that looks like `vpc-opensearch-XXX.eu-central-1.es.amazonaws.com`.
When going through a tunnel one has to provide the `Host` header which should then be taken into consideration when calculating the signature. Otherwise it'll use `https://localhost...` and when the request reaches AWS it will fail with _The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details._

I added the `Host` header to my call, but it seems like it's being ignored for the signature calculation.
I double checked using other tools such as `awscurl` and the same call is working fine there.

Can you confirm this behaviour? Any trick to get around this and make it use the `host` header?

Thanks!

--

UPDATE:
I just checked and it seems like [this line](https://github.com/badslug/Paw-AWSSignature4DynamicValue/blob/develop/AWSSignature4DynamicValue.js#L254) will take the host from the request URI and not from the `host` header. This would explain the issue.

**Comment by badslug** [comment]
Hi

I'm traveling this week but will look into it next week. Sorry for the delay. Definitely would love for it to work for your use-case. 

-iain

**Comment by badslug** [comment]
@riy Hi, sorry for the slow response on this. I got back from my trip and was busy catching back up with work and home stuff. My goal is to have a fix within a couple days and push the extension update to Lucky Marmot for approval by the end of the week. I'm going to ask that you test my change if you have the time but the change I have in mind seems simple enough that it definitely won't be a blocker if you don't have the time or have lost interest in this issue. Thanks

**Comment by riy** [comment]
No worries, @badslug. I appreciate you circling back to this issue :-)

Yes, this is still relevant to me, and if you can deploy a fix/change I will test it and give feedback.

**Comment by badslug** [comment]
Sorry @riy for the delay. I posted PR #33 with a change that should work. To test, please uninstall the normal extension, check out the PR/branch, open a terminal to the project root and run `make` to install the extension into Paw. If you are using Paw from Setapp, you'll need to change the Makefile to use the Setapp version of Paw's container name (it's documented in the README). If you could side load this, and then test it with your proxy I'd greatly appreciate it. Thanks!

**Comment by riy** [comment]
Thank you, @badslug!
I just commented in PR #33. I think there is still an issue somewhere, and my assumption that using the `host` header for the signature calculation would suffice may not be correct.

**Comment by badslug** [comment]
@riy so glad you found the issue and sent the PR. I approved and merged it in. I need to package up the change and send it to Lucky Marmot so they can update their database so the new version shows up in their extension marketplace. (Typically it takes a few days because it is a manual process.) I'll poke this issue again when I submit it to Lucky Marmot and again (and close it) when they tell me it's been updated.

**Comment by riy** [comment]
@badslug 
It was just a minor contribution from my side. Thank YOU for implementing the actual feature :-)
I'll stick with the manually installed version for now and update the Extension whenever Lucky Marmot has the official release.

Thanks again and have a great weekend!

**Comment by badslug** [comment]
Great! You have a good weekend too. I sent the request to Lucky Marmot. I'll let you know when they respond.

**Comment by badslug** [comment]
@riy FYI Lucky Marmot updated the extension link in their database. You can switch back to the one from their "store" whenever you want. I'm closing the issue as done. Thanks for your help!

**Comment by riy** [comment]
Yep, looks good. Thanks for letting me know!

![image](https://user-images.githubusercontent.com/903321/168863561-da38d1c1-a373-48b1-8f45-9a192adf283c.png)
