### ISSUE TITLE
Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header.

### ISSUE THREAD

**Issue by webjay** [badslug/Paw-AWSSignature4DynamicValue#5]
I fixed it by adding `x-amz-date` and set it to custom formatting: `%G%m%dT%H%M%SZ`.

But I get:

```
HTTP/1.1 403 Forbidden
Content-Type: application/json
Content-Length: 68
Connection: close
Date: Fri, 07 Oct 2016 14:52:14 GMT
x-amzn-ErrorType: UnrecognizedClientException
x-amzn-RequestId: xxx
X-Cache: Error from cloudfront
Via: 1.1 xxx.cloudfront.net (CloudFront)
X-Amz-Cf-Id: xxx

{"message":"The security token included in the request is invalid."}
```

Any clues?

**Comment by badslug** [comment]
Sorry for being so long in replying. I think the date header is case sensitive. Please try to change the header name to `X-Amz-Date`. If that doesn't help, can you please post the entire raw request that is sent. There may be some conflicts with other headers you may be sending (e.g. issue #4 ).
