### ISSUE TITLE
Signature Invalid for Create APIs

### ISSUE THREAD

**Issue by paritosh16** [badslug/Paw-AWSSignature4DynamicValue#7]
**Environment Details -** 

1. Operating System - Mac OSX 10.12.1
2. Paw Version - 3.0.12 (Retail)
3. Build - 067B76 (3000012001)

**Steps to reproduce -**

HTTP Headers - 

    1. Content-Type - application/x-www-form-urlencoded 
    2. Host - iam.amazonaws.com
    3. X-Amz-Date - Any UTC date within the last 15 minutes.
    4. Authorization - AWS Signature 4 Auth Extension (parameters to the extension would include 
    Access Key, Secret Access Key, region - 'us-east-1' and service - 'iam')

Use Case 1 - 

URL Params - 

    1. Action - CreateRole
    2. Version - 2010-05-08
    3. RoleName - <name_of_the_role_you_wish_for>
    4. AssumeRolePolicyDocument - <any_valid_policy_document>

Use Case 2 - 

URL Params - 

    1. Action - ListUsers
    2. Version - 2010-05-08

**The bug -**

Use case 1 which tried to create a role errors out because the signature is not valid. Use case 2 succeeds with a proper user list being returned. When I dug deeper into what is changing in the two requests, I noticed that only thing that would change the canonical request is the `AssumeRolePolicyDocument`.

I found out that the `:` in the policy document  were not percent encoded as recommended by amazon. Because the `:` remain as is, the signature is not as Amazon expected it to be, hence the failure.

**References -** 

1. Please refer bullet 3 in [this](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) link for the guidelines on the encoding of the canonical request.
2. Please refer [this](https://awspolicygen.s3.amazonaws.com/policygen.html) link to generate a valid policy document.

**Comment by badslug** [comment]
Hi,

Sorry it's taken so long to get to this bug. I have some bug fixes in the newest version of the Paw extension (version 1.0.5). Can you please try it out and let me know if the issue still exists. Thanks.

**Comment by badslug** [comment]
If anyone has the time, I'd appreciate any testing to confirm this still is broken on the latest release (1.0.7). Thanks

**Comment by DeeGeeMan** [comment]
I am getting an error when calling DescribeRegions from ec2.amazonaws.com.
_Error: The request must contain the parameter AWSAccessKeyId_

I was able to successfully use [AWS python example](http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html) with my API keys.

**Comment by badslug** [comment]
Hi Devin-Grant,

This extension only provides the signed authorization header value according to the amazon signature 4 spec. I believe that error indicates you are calling an endpoint that expects signature 2 authorization. Is that possible?
